version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - yarn install
  builds:
    commands:
      - yarn build
artifacts:
  files:
    - start-service.sh    
    - stop.service.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'